export enum GroupReducerTypes {
  SHOW_DIALOG_TRASH = 'SHOW_DIALOG_TRASH',
  SHOW_DIALOG_CREATE_GROUP = 'SHOW_DIALOG_CREATE_GROUP',
  INPUT_ERROR_GROUP = 'INPUT_ERROR_GROUP',
  NEW_GROUP_VALUE = 'NEW_GROUP_VALUE',
  CLICKED_GROUP = 'CLICKED_GROUP',
  GET_NAME_SELECTED = 'GET_NAME_SELECTED',
  GROUPS = 'GROUPS',
  DELETE_GROUP = 'DELETE_GROUP',
  SHOW_DIALOG_EDIT_GROUP = 'SHOW_DIALOG_EDIT_GROUP',
  EDIT_GROUP = 'EDIT_GROUP',
  HAS_ERROR = 'HAS_ERROR',
  FLASH_SUCCESS_TEXT = 'FLASH_SUCCESS_TEXT',
  IS_VISIBLE = 'IS_VISIBLE',
  FLASH_ERROR_TEXT = 'FLASH_ERROR_TEXT',
  CONTACTS = 'CONTACTS',
  CONTACTS_TRASH = 'CONTACTS_TRASH',
  CONTACTS_FREE_NUMBERS = 'CONTACTS_FREE_NUMBERS',
  CONTACTS_GROUPS = 'CONTACTS_GROUPS',
}
export enum GroupReducerPayload {
  stringEmpty = '',
  renameContact = 'Książka Adresowa',
}
