export enum HomeReducerTypes {
  SHOW_HEADER = 'SHOW_HEADER',
  SEARCH_CONTACTS = 'SEARCH_CONTACTS',
  SHOW_OPTION_SELECTED = 'SHOW_OPTION_SELECTED',
  IS_CHECKED = 'IS_CHECKED',
  CHECKED_CONTACTS = 'CHECKED_CONTACTS',
  SHOW_OPTION_CONTACT = 'SHOW_OPTION_CONTACT',
  CONTAINER_HEIGHT = 'CONTAINER_HEIGHT',
  PREVIEW_CONTACT = 'PREVIEW_CONTACT',
}
