export const RoutePath = {
  home: '/',
  loginRoute: '/login',
  adressBookRoute: '/adress-book',
  createContactRoute: '/adress-book/create-contact',
  allGroups: '/groups',
  contactPreview: '/adress-book/person/',
  createContact: '/adress-book/create-contact',
  trashRoute: '/adress-book/kosz',
  idContact: '/adress-book/:id',
  PreviewContact: '/adress-book/person/:id',
  editContact: '/adress-book/person/:id/edit',
  all: '*',
}

export const FetchPath = {
  home: '/',
  loginPath: '/login',
  adressBook: '/AdressBook',
  checkUser: '/checkUser',
  checkConnect: '/checkConnect',
  createGroup: '/createGroup',
  AllGroups: '/groups',
  saveContactPath: '/createContact',
  allContacts: '/contacts',
  AllContactsTrash: '/contacts/trash',
  allContactsFreeNumbers: '/contacts/free-numbers',
  allContactsGroups: '/contacts/groups',
  deleteContact: '/contact/delete/',
  deleteContactMany: '/contact/deleteMany/',
  editContact: '/contact/edit/',
  groupChange: '/contact/edit/group/',
}
